db:
  current: sqlite3
  sqlite3:
    adapter: sqlite3
    database: /home/ram/cb.sqlite3
  postgresql:
    adapter: postgresql
    database: crunchbase
    username: rafael
    password: 
    host: localhost
data:
  dir: /home/ram

